### ISSUE TITLE
[BUG, ERROR]Get error when do npm start.

### ISSUE THREAD

**Issue by KevinZhang19870314** [looeee/discoverthreejs-site#64] opened 2022-08-12 08:04 UTC
When I follow the `Developer Guide` to run this repo locally, I am getting below error:
```
PS D:\kevinzhang\study\3D\discoverthreejs-site> npm start

> discover-threejs@1.0.0 start D:\kevinzhang\study\3D\discoverthreejs-site
> npm run copy-three && cross-env NODE_ENV=dev npm run run-hugo


> discover-threejs@1.0.0 copy-three D:\kevinzhang\study\3D\discoverthreejs-site
> node scripts/copy-three.cjs

Copying three.js V0.136.0 to examples folder...

> discover-threejs@1.0.0 run-hugo D:\kevinzhang\study\3D\discoverthreejs-site
> node scripts/run-hugo.cjs

Start building sites … 
hugo v0.92.0-B3549403+extended windows/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
INFO 2022/08/12 15:54:44 syncing static files to D:\kevinzhang\study\3D\discoverthreejs-site\
INFO 2022/08/12 15:54:47 postcss: Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
INFO 2022/08/12 15:54:47 postcss: Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
INFO 2022/08/12 15:54:48 postcss: Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/appendix title: 附录
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/appendix/html-and-css-reference title: HTML, CSS
ERROR 2022/08/12 15:54:49 Page not found. URL: book/appendix/dom-api-reference/#your-browser-s-developer-console title: 
浏览器开发者控制台
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/appendix/javascript-reference title: JavaScript
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/appendix/javascript-modules title: 模块
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/appendix/asynchronous-javascript title: 异步编码模式
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/first-steps/_index.md title: 主章节
ERROR 2022/08/12 15:54:49 Page not found. URL: book/appendix title: 附录
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/first-steps/transformations title: 1.5：变换和坐标系
ERROR 2022/08/12 15:54:49 Page not found. URL: /book/first-steps/load-models title: 1.13：加载 glTF 格式的 3D 模型
......
```

What happened, any help?

**Comment by KevinZhang19870314** [comment] 2022-08-12 08:18
Finally, I know it was caused by my translation file xxx.zh.md, unfortunately I don't know how to fix it...

**Comment by bruno-j** [comment] 2022-08-26 14:47
Right now, with this Chinese translation, the building process fails. 

In order to successfully build the English version of the site, remove these two lines in the config.yaml file :

`  zh:
    languageName: 中文
    weight: 2
`

**Comment by looeee** [comment] 2022-08-26 22:46
Thanks for the workaround @bruno-j I'll take a look and see what the issue is.

**Comment by looeee** [comment] 2022-08-31 08:29
@bruno-j and @KevinZhang19870314 this should be fixed now. 

When I started writing the book, Hugo did not manage internal links well so I wrote a custom link short code which looked like this:

`{{< link path="/book/appendix/dom-api-reference/#the-virtual-viewport" title="link text" >}}`

Something in the translated chapters was breaking this which is why `npm start` was failing. 

However the shortcode is no longer needed because Hugo has added better internal link management since then. We can now use [Hugo relref](https://gohugo.io/functions/relref/) for internal links. So the above link becomes this:

`[Link Text]({{< relref "/book/appendix/dom-api-reference#the-virtual-viewport" >}} "Link Title")`

Note there is no trailing slash after `dom-api-reference` in the new format! 

I have converted all internal links to the new format and removed the link shortcode. Building the book with translations enabled should be working now.

**Comment by KevinZhang19870314** [comment] 2022-09-01 01:00
> @bruno-j and @KevinZhang19870314 this should be fixed now.
> 
> When I started writing the book, Hugo did not manage internal links well so I wrote a custom link short code which looked like this:
> 
> `{{< link path="/book/appendix/dom-api-reference/#the-virtual-viewport" title="link text" >}}`
> 
> Something in the translated chapters was breaking this which is why `npm start` was failing.
> 
> However the shortcode is no longer needed because Hugo has added better internal link management since then. We can now use [Hugo relref](https://gohugo.io/functions/relref/) for internal links. So the above link becomes this:
> 
> `[Link Text]({{< relref "/book/appendix/dom-api-reference#the-virtual-viewport" >}} "Link Title")`
> 
> Note there is no trailing slash after `dom-api-reference` in the new format!
> 
> I have converted all internal links to the new format and removed the link shortcode. Building the book with translations enabled should be working now.

Thank you for your fix, I'll go ahead and do translation using the `Hugo relref format`.

**Comment by looeee** [comment] 2022-09-01 03:51
@KevinZhang19870314 I have updated all the existing links in your translations (opefully without breaking anything!). Make sure to merge in the master branch.

**Comment by KevinZhang19870314** [comment] 2022-09-01 05:48
> @KevinZhang19870314 I have updated all the existing links in your translations (opefully without breaking anything!). Make sure to merge in the master branch.

It should be `main` branch?

**Comment by looeee** [comment] 2022-09-01 07:59
Yes sorry, the main branch. 

Actually I was wrong earlier, the links were still broken. Sorry for any confusion. If you merge in main now it should be working. 

I've also reorganized the `markdown/` folder  to make translations easier. 

There's now two separate folders and all the Chinese translations will go in the `zh` folder which is a mirror of the `en` folder. 

![en zh](https://user-images.githubusercontent.com/5307958/187862471-5845c246-8a12-41f5-a48d-d0b7c0cb3794.png)

So if there is `markdown/en/book/animation-loop.md` the Chinese translation will be in `markdown/zh/book/animation-loop.md`.

There's no need to call the translated file `.zh.md` anymore.

**Comment by looeee** [comment] 2022-09-01 08:00
The `zh` folder has to include _all_ the same files as the `en` folder, even if they are not translated yet! 

So, for example, `markdown/zh/book/animation-loop.md` is still in English right now.

**Comment by KevinZhang19870314** [comment] 2022-09-01 08:19
> The `zh` folder has to include _all_ the same files as the `en` folder, even if they are not translated yet!
> 
> So, for example, `markdown/zh/book/animation-loop.md` is still in English right now.

@looeee Yes, it works in my local environment! With the new folder structure, its clear enough!
![image](https://user-images.githubusercontent.com/13794286/187866938-62c57b36-b968-4880-afb3-535da6bd4805.png)

**Comment by looeee** [comment] 2022-09-01 09:59
Great! In that case I will close this issue.

**Closed by looeee** 2022-09-01 09:59 UTC
